spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pedidos-route
          uri: lb://ms-pedidos
          predicates:
            - Path=/pedidos/**
        - id: pagamentos-route
          uri: lb://ms-pagamentos
          predicates:
            - Path=/pagamentos/**
server:
  port: 8080
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/