spring:
    application:
        name: total-shake-discovery-server
server:
  port: 8761

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka